# Generated by Django 5.1.3 on 2025-04-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userImg',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
    ]
