# Generated by Django 5.1.3 on 2024-11-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_discussionboard_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionboard',
            name='board_image',
            field=models.ImageField(blank=True, null=True, upload_to='disc_boards/'),
        ),
    ]
