# Generated by Django 5.1.3 on 2025-04-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comment_downvotes_post_downvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content_moderation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='content_moderation',
            field=models.BooleanField(default=False),
        ),
    ]
